### ISSUE TITLE
[request] transit support

### ISSUE THREAD

**Issue by snoe** [clumsyjedi/clack#4]
great tool! most of our services communicate using transit, it would be great if clack could also read (and detect?) transit and convert to edn.

**Comment by clumsyjedi** [comment]
Hi thanks,

Have a look at my latest [commit](https://github.com/clumsyjedi/clack/commit/a6937defcbd985de0b95b9a027bcfd4bfa29c527), hopefully this will meet your needs re: transit. I don't actually use transit for anything, so I  havea poor grasp on what is actually useful.

`echo "[\"^ \",\"foo\",null]" | clack -i tjs -o edn` will convert basic transit to edn
`echo "{:foo nil}" | clack -i edn -o tjs` will convert the other way

I would be interested to know if this is useful to you before I close it.

**Comment by snoe** [comment]
This works great, thanks!
